// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_38e280b800d194745adabb5e62df9271_b9dd199cf681431c9f0fea75b880b162 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_38e280b800d194745adabb5e62df9271 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_38e280b800d194745adabb5e62df9271>();
        
        private global::GameFlow _38e280b800d194745adabb5e62df9271_4373085ace234ad9a7db019e3374a185_CommandTarget;
        private global::GameFlow _38e280b800d194745adabb5e62df9271_04a0ec25eaf34733950c64b1111982f1_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["b9dd199cf681431c9f0fea75b880b162"] = new Binding_38e280b800d194745adabb5e62df9271_b9dd199cf681431c9f0fea75b880b162(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_38e280b800d194745adabb5e62df9271()
        {
            bakedCommandBindings.Add("4373085ace234ad9a7db019e3374a185", BakeCommandBinding__38e280b800d194745adabb5e62df9271_4373085ace234ad9a7db019e3374a185);
            bakedCommandBindings.Add("04a0ec25eaf34733950c64b1111982f1", BakeCommandBinding__38e280b800d194745adabb5e62df9271_04a0ec25eaf34733950c64b1111982f1);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__38e280b800d194745adabb5e62df9271_4373085ace234ad9a7db019e3374a185(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _38e280b800d194745adabb5e62df9271_4373085ace234ad9a7db019e3374a185_CommandTarget = (global::GameFlow)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"GameFlow.ApplyActorMoveCommand",
            	"(System.Int32System.Int32System.Int32)",
            	SendCommand__38e280b800d194745adabb5e62df9271_4373085ace234ad9a7db019e3374a185,
            	ReceiveLocalCommand__38e280b800d194745adabb5e62df9271_4373085ace234ad9a7db019e3374a185,
            	MessageTarget.All,
            	_38e280b800d194745adabb5e62df9271_4373085ace234ad9a7db019e3374a185_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__38e280b800d194745adabb5e62df9271_4373085ace234ad9a7db019e3374a185(GenericCommandRequestArgs requestArgs)
        {
            var command = new _38e280b800d194745adabb5e62df9271_4373085ace234ad9a7db019e3374a185();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.actorId = (System.Int32)requestArgs.Args[0];
            command.targetX = (System.Int32)requestArgs.Args[1];
            command.targetY = (System.Int32)requestArgs.Args[2];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__38e280b800d194745adabb5e62df9271_4373085ace234ad9a7db019e3374a185(GenericCommandRequestArgs requestArgs)
        {
            var command = new _38e280b800d194745adabb5e62df9271_4373085ace234ad9a7db019e3374a185();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.actorId = (System.Int32)requestArgs.Args[0];
            command.targetX = (System.Int32)requestArgs.Args[1];
            command.targetY = (System.Int32)requestArgs.Args[2];

            ReceiveCommand__38e280b800d194745adabb5e62df9271_4373085ace234ad9a7db019e3374a185(command);
        }

        private void ReceiveCommand__38e280b800d194745adabb5e62df9271_4373085ace234ad9a7db019e3374a185(_38e280b800d194745adabb5e62df9271_4373085ace234ad9a7db019e3374a185 command)
        {
			var target = _38e280b800d194745adabb5e62df9271_4373085ace234ad9a7db019e3374a185_CommandTarget;
			target.ApplyActorMoveCommand((System.Int32)(command.actorId),(System.Int32)(command.targetX),(System.Int32)(command.targetY));
        }
        private void BakeCommandBinding__38e280b800d194745adabb5e62df9271_04a0ec25eaf34733950c64b1111982f1(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _38e280b800d194745adabb5e62df9271_04a0ec25eaf34733950c64b1111982f1_CommandTarget = (global::GameFlow)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"GameFlow.ApplyTurnEndCommand",
            	"()",
            	SendCommand__38e280b800d194745adabb5e62df9271_04a0ec25eaf34733950c64b1111982f1,
            	ReceiveLocalCommand__38e280b800d194745adabb5e62df9271_04a0ec25eaf34733950c64b1111982f1,
            	MessageTarget.All,
            	_38e280b800d194745adabb5e62df9271_04a0ec25eaf34733950c64b1111982f1_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__38e280b800d194745adabb5e62df9271_04a0ec25eaf34733950c64b1111982f1(GenericCommandRequestArgs requestArgs)
        {
            var command = new _38e280b800d194745adabb5e62df9271_04a0ec25eaf34733950c64b1111982f1();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__38e280b800d194745adabb5e62df9271_04a0ec25eaf34733950c64b1111982f1(GenericCommandRequestArgs requestArgs)
        {
            var command = new _38e280b800d194745adabb5e62df9271_04a0ec25eaf34733950c64b1111982f1();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;


            ReceiveCommand__38e280b800d194745adabb5e62df9271_04a0ec25eaf34733950c64b1111982f1(command);
        }

        private void ReceiveCommand__38e280b800d194745adabb5e62df9271_04a0ec25eaf34733950c64b1111982f1(_38e280b800d194745adabb5e62df9271_04a0ec25eaf34733950c64b1111982f1 command)
        {
			var target = _38e280b800d194745adabb5e62df9271_04a0ec25eaf34733950c64b1111982f1_CommandTarget;
			target.ApplyTurnEndCommand();
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _38e280b800d194745adabb5e62df9271_4373085ace234ad9a7db019e3374a185 castedCommand:
                    ReceiveCommand__38e280b800d194745adabb5e62df9271_4373085ace234ad9a7db019e3374a185(castedCommand);
                    break;
                case _38e280b800d194745adabb5e62df9271_04a0ec25eaf34733950c64b1111982f1 castedCommand:
                    ReceiveCommand__38e280b800d194745adabb5e62df9271_04a0ec25eaf34733950c64b1111982f1(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_38e280b800d194745adabb5e62df9271 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_38e280b800d194745adabb5e62df9271>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
