// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_31c8ee0907a477240a7a22f500499697_be4c59ef7ee749efb80d11f5cb6b8b47 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_31c8ee0907a477240a7a22f500499697 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_31c8ee0907a477240a7a22f500499697>();
        
        private global::PlayerCommands _31c8ee0907a477240a7a22f500499697_6473b1476e6d44a4b4f06f1b318acf34_CommandTarget;
        private global::PlayerCommands _31c8ee0907a477240a7a22f500499697_fe954be45272475db028e2cfc06936bf_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["be4c59ef7ee749efb80d11f5cb6b8b47"] = new Binding_31c8ee0907a477240a7a22f500499697_be4c59ef7ee749efb80d11f5cb6b8b47(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_31c8ee0907a477240a7a22f500499697()
        {
            bakedCommandBindings.Add("6473b1476e6d44a4b4f06f1b318acf34", BakeCommandBinding__31c8ee0907a477240a7a22f500499697_6473b1476e6d44a4b4f06f1b318acf34);
            bakedCommandBindings.Add("fe954be45272475db028e2cfc06936bf", BakeCommandBinding__31c8ee0907a477240a7a22f500499697_fe954be45272475db028e2cfc06936bf);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__31c8ee0907a477240a7a22f500499697_6473b1476e6d44a4b4f06f1b318acf34(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _31c8ee0907a477240a7a22f500499697_6473b1476e6d44a4b4f06f1b318acf34_CommandTarget = (global::PlayerCommands)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"PlayerCommands.ApplyActorMoveCommand",
            	"(System.Int32System.Int32System.Int32)",
            	SendCommand__31c8ee0907a477240a7a22f500499697_6473b1476e6d44a4b4f06f1b318acf34,
            	ReceiveLocalCommand__31c8ee0907a477240a7a22f500499697_6473b1476e6d44a4b4f06f1b318acf34,
            	MessageTarget.All,
            	_31c8ee0907a477240a7a22f500499697_6473b1476e6d44a4b4f06f1b318acf34_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__31c8ee0907a477240a7a22f500499697_6473b1476e6d44a4b4f06f1b318acf34(GenericCommandRequestArgs requestArgs)
        {
            var command = new _31c8ee0907a477240a7a22f500499697_6473b1476e6d44a4b4f06f1b318acf34();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.actorId = (System.Int32)requestArgs.Args[0];
            command.targetX = (System.Int32)requestArgs.Args[1];
            command.targetY = (System.Int32)requestArgs.Args[2];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__31c8ee0907a477240a7a22f500499697_6473b1476e6d44a4b4f06f1b318acf34(GenericCommandRequestArgs requestArgs)
        {
            var command = new _31c8ee0907a477240a7a22f500499697_6473b1476e6d44a4b4f06f1b318acf34();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.actorId = (System.Int32)requestArgs.Args[0];
            command.targetX = (System.Int32)requestArgs.Args[1];
            command.targetY = (System.Int32)requestArgs.Args[2];

            ReceiveCommand__31c8ee0907a477240a7a22f500499697_6473b1476e6d44a4b4f06f1b318acf34(command);
        }

        private void ReceiveCommand__31c8ee0907a477240a7a22f500499697_6473b1476e6d44a4b4f06f1b318acf34(_31c8ee0907a477240a7a22f500499697_6473b1476e6d44a4b4f06f1b318acf34 command)
        {
			var target = _31c8ee0907a477240a7a22f500499697_6473b1476e6d44a4b4f06f1b318acf34_CommandTarget;
			target.ApplyActorMoveCommand((System.Int32)(command.actorId),(System.Int32)(command.targetX),(System.Int32)(command.targetY));
        }
        private void BakeCommandBinding__31c8ee0907a477240a7a22f500499697_fe954be45272475db028e2cfc06936bf(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _31c8ee0907a477240a7a22f500499697_fe954be45272475db028e2cfc06936bf_CommandTarget = (global::PlayerCommands)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"PlayerCommands.ApplyTurnEndCommand",
            	"()",
            	SendCommand__31c8ee0907a477240a7a22f500499697_fe954be45272475db028e2cfc06936bf,
            	ReceiveLocalCommand__31c8ee0907a477240a7a22f500499697_fe954be45272475db028e2cfc06936bf,
            	MessageTarget.All,
            	_31c8ee0907a477240a7a22f500499697_fe954be45272475db028e2cfc06936bf_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__31c8ee0907a477240a7a22f500499697_fe954be45272475db028e2cfc06936bf(GenericCommandRequestArgs requestArgs)
        {
            var command = new _31c8ee0907a477240a7a22f500499697_fe954be45272475db028e2cfc06936bf();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__31c8ee0907a477240a7a22f500499697_fe954be45272475db028e2cfc06936bf(GenericCommandRequestArgs requestArgs)
        {
            var command = new _31c8ee0907a477240a7a22f500499697_fe954be45272475db028e2cfc06936bf();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;


            ReceiveCommand__31c8ee0907a477240a7a22f500499697_fe954be45272475db028e2cfc06936bf(command);
        }

        private void ReceiveCommand__31c8ee0907a477240a7a22f500499697_fe954be45272475db028e2cfc06936bf(_31c8ee0907a477240a7a22f500499697_fe954be45272475db028e2cfc06936bf command)
        {
			var target = _31c8ee0907a477240a7a22f500499697_fe954be45272475db028e2cfc06936bf_CommandTarget;
			target.ApplyTurnEndCommand();
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _31c8ee0907a477240a7a22f500499697_6473b1476e6d44a4b4f06f1b318acf34 castedCommand:
                    ReceiveCommand__31c8ee0907a477240a7a22f500499697_6473b1476e6d44a4b4f06f1b318acf34(castedCommand);
                    break;
                case _31c8ee0907a477240a7a22f500499697_fe954be45272475db028e2cfc06936bf castedCommand:
                    ReceiveCommand__31c8ee0907a477240a7a22f500499697_fe954be45272475db028e2cfc06936bf(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_31c8ee0907a477240a7a22f500499697 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_31c8ee0907a477240a7a22f500499697>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
